### ISSUE TITLE
Add mergify support to QGB branch

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#1018]
### Summary

Update the QGB v1 branch using mergify automatically to stay up to date with latest main changes

### Problem Definition

If we're planning to support QGB v1 until QGB v2 is ready, we will need to keep it up to date with the latest main changes. This would be easier if we have mergify setup to handle this.

### Proposal

- [ ] Rename the `qgb-integration` branch to `qgb-v1`
- [ ] Add the following to mergify script:
```
  - name: backport patches to qgb-v1 branch
    conditions:
      - base=main
      - label=S:backport-to-qgb-v1
    actions:
      backport:
        branches:
          - qgb-v1
```

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
