### ISSUE TITLE
The browser is not displaying `validator` data effectively.

### ISSUE THREAD

**Issue by 99Kies** [celestiaorg/celestia-app#1848]
### Summary of Bug

I successfully created the validator, but my validator information is not displayed in the browser.

<img width="1350" alt="image" src="https://github.com/celestiaorg/celestia-app/assets/45918704/954bb965-967b-45db-ac7a-c02dceec1227">

this is my validator addr: `celestiavaloper1lxxulmef5tcsxtn769kfj0z9kucw57kdgy9cah`

### Version

mocha testnet

### Steps to Reproduce

this is my `tx`: `https://testnet.mintscan.io/celestia-testnet/txs/4F78A26499F838D3908EFEFB17A4DE4A61CE269B9ADA8CF1FBD22C06175D5809`

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by rootulp** [comment]
Thanks for creating an issue @99Kies ! Can you please elaborate on

> is not displayed in the browser

Specifically can you answer these questions:

1. Which website do you expect to see your validator? Is it https://testnet.mintscan.io/celestia-testnet/validators/celestiavaloper1lxxulmef5tcsxtn769kfj0z9kucw57kdgy9cah ? If not can you share a link?
3. What do you expect to see?
4. What are you seeing instead? Can you please share a screenshot?
5. What browser are you using? 
6. What browser version are you using?

I don't see "Dora Factory PGS" on https://testnet.mintscan.io/celestia-testnet/validators so I suspect this is a Mintscan issue rather than a celestia-app issue.

**Comment by evan-forbes** [comment]
this is likely because the validator does not have enough stake to be included in the validator set

**Comment by rootulp** [comment]
Hmm but inactive validators appear to display on https://testnet.mintscan.io/celestia-testnet/validators via 

<img width="320" alt="Screenshot 2023-05-29 at 10 34 31 AM" src="https://github.com/celestiaorg/celestia-app/assets/3699047/210f1928-7861-4da9-874f-8f7e39b322ea">

**Comment by evan-forbes** [comment]
oh cool didn't know they had that

this is the result from querying a full node
```
commission:
  commission_rates:
    max_change_rate: "1.000000000000000000"
    max_rate: "1.000000000000000000"
    rate: "1.000000000000000000"
  update_time: "2023-05-27T07:19:31.143677366Z"
consensus_pubkey:
  '@type': /cosmos.crypto.ed25519.PubKey
  key: rHCcBqvFJX3N7j4/5IeKCkmB1A1t1f6WIAcZ3VjfCNQ=
delegator_shares: "2000000.000000000000000000"
description:
  details: ""
  identity: ""
  moniker: Dora Factory PGS
  security_contact: ""
  website: ""
evm_address: celestia1lxxulmef5tcsxtn769kfj0z9kucw57kddm8pt3
jailed: false
min_self_delegation: "1000000"
operator_address: celestiavaloper1lxxulmef5tcsxtn769kfj0z9kucw57kdgy9cah
status: BOND_STATUS_UNBONDED
tokens: "2000000"
unbonding_height: "0"
unbonding_time: "1970-01-01T00:00:00Z"
```
not sure why that's not showing up on mintscan
