### ISSUE TITLE
Consider enabling `duplicated-imports` for revive

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2155]
## Context

Revive doesn't catch duplicate imports by default

## Problem

If a dependency is imported twice with different names, revive won't warn you

```go
tmtypes "github.com/cometbft/cometbft/types"
cmtypes "github.com/cometbft/cometbft/types"
```

## Proposal

```yaml
linters-settings:
  revive:
    rules:
      - name: duplicated-imports
        severity: warning
```
