### ISSUE TITLE
Signing Binaries

### ISSUE THREAD

**Issue by MSevey** [celestiaorg/celestia-app#2445]
### Summary

As a follow up from introducing [Goreleaser](https://goreleaser.com/) in #2437 consider signing binaries.

### Problem Definition

Without signatures, users can't verify the binary downloaded was the one built by the team.

### Proposal

REF: https://goreleaser.com/customization/sign/

The github workflow would need the following update:
```yml     
      # Import the GPG key from github secrets to sign the binaries
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_SIGNING_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      # Generate the binaries, release, and sign the checksum
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BuildTags: ${{ needs.build_tags.outputs.BUILDTAGS }}
          BuildTagsCommaSep: ${{ needs.build_tags.outputs.BUILDTAGSCOMMASEP }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
```
The `.goreleaser.yaml` file needs the following update:
```yml
signs:
  - artifacts: checksum
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]
```

A GPG secret key and passphrase will need to be created and added to the repo's github secrets. The secret's names shold be `GPG_SIGNING_KEY` and `GPG_PASSPHRASE`.

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
