### ISSUE TITLE
Release Process Updates

### ISSUE THREAD

**Issue by MSevey** [celestiaorg/celestia-app#2451]
It came up in the Goreleaser PR #2437 that the team isn't using the CI for the release process.  If the team would like to begin using the CI for the release process, for goreleaser to auto build the binaries and generate the release, then we should align on the process and make the corresponding updates to the CI.             
            
            
            
            
              [no change needed][follow up refactor] I only ever cut celestia-app releases with via the **Draft a new release** button on [celestia-app/releases](https://github.com/celestiaorg/celestia-app/releases) so that I can manually inspect the auto-generated release notes. AFAIK cutting a release via that page doesn't qualify as a [`workflow_dispatch`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) event. If that's also how @evan-forbes cuts releases, then we may not need this step and can potentially drop this section above:

```
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: "Semver type of new version (major / minor / patch)"
        # Input has to be provided for the workflow to run
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
```

_Originally posted by @rootulp in https://github.com/celestiaorg/celestia-app/pull/2437#discussion_r1317399036_
