### ISSUE TITLE
markdown-linter doesn't run on PRs to main

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2555]
## Context

We recently introduced a new CI workflow: https://github.com/celestiaorg/celestia-app/blob/9efd8b7fb9dabb551ebeb946baf829d3dd2f2323/.github/workflows/markdown-linter.yml

## Problem

markdown-linter isn't run on https://github.com/celestiaorg/celestia-app/pull/2554

### Option A

Add this to https://github.com/celestiaorg/celestia-app/blob/9efd8b7fb9dabb551ebeb946baf829d3dd2f2323/.github/workflows/markdown-linter.yml

```yaml
on:
  push:
    branches:
      - main
      - "v[0-9]+.x"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"
  pull_request:
```

### Option B

Make https://github.com/celestiaorg/celestia-app/blob/main/.github/workflows/ci-release.yml invoke markdown-linter
