### ISSUE TITLE
Missing blocks without any obvious issues

### ISSUE THREAD

**Issue by zheli** [celestiaorg/celestia-app#3080]
### Summary of Bug

Between Jan 6th 00:39:45 UTC to 02:03:15, a large percentage of validators missed blocks without any particular reasons
![missing_blocks](https://github.com/celestiaorg/celestia-app/assets/157039/313308a9-1a80-44b3-91e1-4999392abf76)
We can confirm that we didn't have any issues with our setup, except 1 out of 3 sentry nodes were in fast sync due to an earlier issue. There were no errors in validator logs other than complaints about the out-of-sync sentry node. Would be great if we can find out what caused this.

See the initial discussion here: https://discord.com/channels/638338779505229824/1169241489776324608/1204373370783670342

### Version

`ghcr.io/celestiaorg/celestia-app:v1.3.0`

### Steps to Reproduce

None.

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by mindstyle85** [comment]
It seems we have observed almost all validators miss a few blocks over night as seen on nodes guru explorer and:

```
- address: celestiavalcons1qf42ufn6eatzkcez3xh5nl3ua49qf5jjk36pfq
  index_offset: "516844"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "9"
  start_height: "206005"
  tombstoned: false
- address: celestiavalcons1qhfwytqjzmxnqyztekmtzg43ulc6edwdn66ekx
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "3"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons1qud7fnf0qjr0997x2vy33qzzvyp5ermunrxmzs
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "2"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons1qlj74lhqxwucjljpxmwlxrvhzhn2ccawecnf7w
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "8"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons1p8zg2kxtnc9epwpghx89u3pyqss5683w7ha2g9
  index_offset: "721966"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "2"
  start_height: "883"
  tombstoned: false
- address: celestiavalcons1pk9xgjl43n7xpnlml3d2cwsdvxed0mtpa2k94j
  index_offset: "1577"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "16"
  tombstoned: false
- address: celestiavalcons1pm02ck4ecxamm06c5nqvhyqhhwpkus3lkp3qcl
  index_offset: "288"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "584"
  tombstoned: false
- address: celestiavalcons1zytmq7hegd04hzuvxkfmndgmd9dv9hs4wpndw4
  index_offset: "721351"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "110773"
  tombstoned: false
- address: celestiavalcons1zfjq8gk25dkmmc8mvjn6uuhds2texehhkxdhyw
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "5"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons1z0asee3hx2m6gzz3n655yjm5pdw5ax2vggq9wp
  index_offset: "76"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "853"
  tombstoned: false
- address: celestiavalcons1zhm6rwntqacqk86n0jhujpmn04pulay0k0k93x
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons1zegpgm683fsfde8eszqrv3hu3m3uxcgrtj5alq
  index_offset: "717522"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "6030"
  tombstoned: false
- address: celestiavalcons1zlszplyjmmjk7vhx2t82e0vdaqsw8krjp9z98g
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "5"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons1r8rrxuptqffqs2jppjq5gsen444ls9xl9dngvt
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons1rtsl3qxpygh0kvxjrwwevcqavtw4s9vnl0ecd4
  index_offset: "130128"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "592721"
  tombstoned: false
- address: celestiavalcons1rea6yz4v7lhjeh4yrn0l3h8dl0839umr3ysh6e
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "8"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons1rljswm4jpy96hghk2lk05wkn7fnwu07xvhye4q
  index_offset: "717875"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "2"
  start_height: "30282"
  tombstoned: false
- address: celestiavalcons1yzkwruvuqewgvpv6chpk29g0wpgs9nwz62dlmc
  index_offset: "940"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "191"
  tombstoned: false
- address: celestiavalcons1yrg6p7dtch47u9s9qlntj72gvurywxapj093c7
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons1y84ag555fp4s7qgfkalrc03g54xgwsm0gkc450
  index_offset: "18566"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "939"
  tombstoned: false
- address: celestiavalcons1y2y8aa0nlh62qsavtd5cxyxyt68u0lrz75hgu5
  index_offset: "722432"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "54688"
  tombstoned: false
- address: celestiavalcons1y20w39d3ghq8akae40p6eq40w9n6yv70mu60cn
  index_offset: "676424"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "3"
  start_height: "54270"
  tombstoned: false
- address: celestiavalcons1y4s93djhxtk8c6utc3x9l5jsyggn0xklhd790m
  index_offset: "68196"
  jailed_until: "2024-01-27T21:46:58.913261807Z"
  missed_blocks_counter: "7"
  start_height: "654655"
  tombstoned: false
- address: celestiavalcons1y6keqvr0xektsjswedq7sv7vl5j4twee4yzt9k
  index_offset: "200"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "36"
  tombstoned: false
- address: celestiavalcons1ymuap0plg9vk62590xztvhwgt5psj38zlzzx37
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "8"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons1ya4r2kkx0dkm6xj9xdwzs4zrd8xqc8hxjglslm
  index_offset: "610"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "1"
  start_height: "559"
  tombstoned: false
- address: celestiavalcons19tufgt5sww9ld4z4heysu9m26ss2nsx58eu6af
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons19a773ks52eacdvpx7pza4jj974t5uljqc6v0ms
  index_offset: "722493"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "12"
  start_height: "356"
  tombstoned: false
- address: celestiavalcons1xxxp3g3x2j44r4jlppvc2w7yshg7zleppnxduf
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "5"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons1xffwfuf2zx7lt6nzwttcmsr4ymh62learjnxq2
  index_offset: "437787"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "7"
  start_height: "362598"
  tombstoned: false
- address: celestiavalcons1xfn6n27l4rr5jc7qtxmt8mumc69qwn9wv00uqs
  index_offset: "722646"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "3"
  start_height: "203"
  tombstoned: false
- address: celestiavalcons1x4apx42xfjh58ahmqftk9fe8u9z244hnp5ndxj
  index_offset: "413938"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "927"
  tombstoned: false
- address: celestiavalcons1xew36m5xkr0xv2rw5cjvzl8qn4xc3ksppz3gl3
  index_offset: "721678"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "55860"
  tombstoned: false
- address: celestiavalcons1xmeh2qnagx7dx2x2ljy6ddmw89ye30n5w4lju9
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "3"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons1x7ndtnskv9rumnwczde0afd87t8872j9zkppdd
  index_offset: "721718"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "1131"
  tombstoned: false
- address: celestiavalcons18rau229csgdzu8vjg2jw9cn0r4zj83mwpzftsq
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "10"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons18h487erc29ty6emyxph3pzfph07zntww7cr4g2
  index_offset: "713764"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "10"
  start_height: "9189"
  tombstoned: false
- address: celestiavalcons187y7g4jee9jre2pjrmy22z2920zskmzv598vfz
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "4"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons1grmryp34dtlewwnzqstcahqkplj6xvttelndmq
  index_offset: "2983"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "1"
  start_height: "142"
  tombstoned: false
- address: celestiavalcons1gd9wymks3x48y4jk8tudlgzfqmf80zgka7a3z6
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "8"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons1f8vl44rn9x6p3tn0laql3e2gcng6kuqrz33maa
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons1f3c40vprfkgye0gkmxf7fhvw49dqwqc0zs569d
  index_offset: "714992"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "8267"
  tombstoned: false
- address: celestiavalcons12prlnu0qe7lyhj69h04q6xh8pwpyxsfdtj9wel
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "7"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons12pgdmteujwpjtynkxrsc64tt5g3st06l4sr890
  index_offset: "152"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "1"
  start_height: "104"
  tombstoned: false
- address: celestiavalcons12pk67urtzn4v2wc8et98fxapdzramnuqttss4j
  index_offset: "569242"
  jailed_until: "2023-11-21T04:35:35.283633681Z"
  missed_blocks_counter: "0"
  start_height: "153609"
  tombstoned: false
- address: celestiavalcons12xhqnl29f2mhh0u85sa3ycuu97n2a7wypu0p04
  index_offset: "152"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "125"
  tombstoned: false
- address: celestiavalcons1225j5r2zm8drtnuhddzprsu5quhx5700zdf9c5
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "6"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons120hzw9695umechc6x489f3w5r6qdlxl5xv2wkm
  index_offset: "722791"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "10"
  start_height: "58"
  tombstoned: false
- address: celestiavalcons12srucpg768mlt05wejzkkps3yxa3wrtekfejfy
  index_offset: "722834"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "1"
  start_height: "15"
  tombstoned: false
- address: celestiavalcons12n74pf2lahqdjvuyyx4n9uyvn2ddvm97kfy0v8
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "10"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons12lktte4mfna7pp2ph9cacfq0x0hv3q9aln69vc
  index_offset: "5890"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "140"
  tombstoned: false
- address: celestiavalcons1t9zfw9m87r6lrvp7pad53c0988ypjm9gkhe3tl
  index_offset: "722245"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "604"
  tombstoned: false
- address: celestiavalcons1ttll3r37y44gfgxfav6gkpzv4ku3yxtmrlx7zy
  index_offset: "122635"
  jailed_until: "2024-01-20T19:04:18.027305163Z"
  missed_blocks_counter: "10"
  start_height: "600216"
  tombstoned: false
- address: celestiavalcons1tm62cuqvxy3dc0zjwwxg032am22nyez6mqgke4
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "45"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons1vtjgwq5e550axzftcrkd2g3tcxykaw5tq3t5ud
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "25"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons1vve9y723tswr4ywhutd347x3huspjj8mrdq7xx
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons1vwnzg3z6wxj7rpess4xwt0sanjfaettwdtm0mk
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "10"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons1vjnfjp7k4cvy2qjsc7pq7lr8wmpvqm7xgm5246
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "5"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons1vn03z8n4nq3pv5vk7wk8q57wp7t9a5z04qckfg
  index_offset: "369239"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "10"
  start_height: "354103"
  tombstoned: false
- address: celestiavalcons1vkh6qcp644hc2nuwcwlc7ypsumg9dpyxhr9zfd
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons1d2x6my3qt6arfvmnarma9gk4qps0lkmcqmxrd6
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons1dvkx8pe0d56q9t44kcttvwhg8xpddd0kh5fkqz
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "1"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons1dkzx5gmw744js3mephurnqdsa6dzsnz3874g4w
  index_offset: "368766"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "354083"
  tombstoned: false
- address: celestiavalcons1wrrt6q8wvnd46c844nytgc5u6cgrg6yfknrdch
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "8"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons1wtrgmmrvaw32jr22elqsjlwnnmr3v6njm6jq8g
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons1wjzc0jyz2g30ldd9p7aptdr087vrk5f0mqnc7k
  index_offset: "77"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "225"
  tombstoned: false
- address: celestiavalcons1wmzarm68ykw5c9cnspztqzw9xs7qg3g63qm9xt
  index_offset: "5777"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "6654"
  tombstoned: false
- address: celestiavalcons1wacan2hcejl04f65p6rz7sk5rskrgq5dut8yjx
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons10x38u88qjgy7gdcfc7yhkdmwzenxmm5ugk2pe5
  index_offset: "5"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "198"
  tombstoned: false
- address: celestiavalcons10tr5076nzac9dkqs6ekn2jhj5uf7jewy0uke2v
  index_offset: "714426"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "7"
  start_height: "8423"
  tombstoned: false
- address: celestiavalcons10vaxc6pchyx9vc7t2n58h9f4jsdg05nmn9j2z8
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "3"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons10085vux20n75xly4j47svkj3u38ft604k3vrdc
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "1"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons1sfm8mswmhg522xzm8tvmxnw89z7tdzwm0mfzrv
  index_offset: "235"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "13503"
  tombstoned: false
- address: celestiavalcons1sdqxg86gshefqnmn8uyqel7hfxm4mxuny04vqp
  index_offset: "620327"
  jailed_until: "2023-11-14T01:49:28.510143667Z"
  missed_blocks_counter: "12"
  start_height: "254778"
  tombstoned: false
- address: celestiavalcons1sdfwea3wlnmahtx7s5hxm87p59vrc9xn7y5xw6
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "3"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons1s53ck6gm7vzl47zsff3v4e2cktcdq4nq5w6ksy
  index_offset: "837"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "695"
  tombstoned: false
- address: celestiavalcons1sewf3f923h8cmefru4p6qnj0m3qf8m3n4rq82d
  index_offset: "721977"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "1"
  start_height: "872"
  tombstoned: false
- address: celestiavalcons13tywu72z67d6cfa4kwxwm5jqf30qmzaa06ywqh
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "6"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons1309x055jhwrte4hr3zs82ypd3zjxhfltghjhg2
  index_offset: "175"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "483"
  tombstoned: false
- address: celestiavalcons1j9jlpc6n8crx6462q6ej432w07h8w8vveesvh6
  index_offset: "273957"
  jailed_until: "2023-12-31T04:28:08.935275692Z"
  missed_blocks_counter: "1"
  start_height: "448894"
  tombstoned: false
- address: celestiavalcons1jc8pzd0xtzd2cr8mr2hxf9dupw3q4p9wwhl2m0
  index_offset: "476"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "1"
  start_height: "128"
  tombstoned: false
- address: celestiavalcons1jlss3xq80xuk885czu5hz3k86hcpdtcdkyrdt2
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons1n9zn9aldrmuhy6e00kuxzwmhh3dyer9wrhl44j
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "7"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons1nw9v2hwn3vvctnpflgamz6jfezkhru6asuas9g
  index_offset: "112069"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "152396"
  tombstoned: false
- address: celestiavalcons1nctah0hh98236tatwayzxsmcx4ev52nawhefm6
  index_offset: "722710"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "139"
  tombstoned: false
- address: celestiavalcons1nm87ew6s58x7g5nvc34jmljlum6mu3uan537nx
  index_offset: "698778"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "6"
  start_height: "30254"
  tombstoned: false
- address: celestiavalcons1nah87vzcenhawdh634h3ctl8xunzxpnc5dmt59
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "4"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons1nam6za6fl9rycfk765z06lt0dvxy7cyhra43wq
  index_offset: "260"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "96"
  tombstoned: false
- address: celestiavalcons15z6df8trdvmq2n79e9rmexunge3nxgu3f3a3cf
  index_offset: "104026"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "112248"
  tombstoned: false
- address: celestiavalcons15y9hgf432y8lj4g8gfkxzf0g78lwwgv98swxf0
  index_offset: "174"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "1"
  start_height: "51"
  tombstoned: false
- address: celestiavalcons15tw4ayu3uk7u0ukm3xd8s4j04sxq0g72kchdet
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "6"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons15wfssk5tysqum8wsrpw85d2r6rv5xgvn2mmx82
  index_offset: "592722"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons153s002vx3c7rrra73apfvedzaqdwg3e30ky224
  index_offset: "708186"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "5"
  start_height: "44946"
  tombstoned: false
- address: celestiavalcons154rx7f484nzgzplr4wpd98ucxeqvrvegtsks08
  index_offset: "704156"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "10"
  start_height: "18693"
  tombstoned: false
- address: celestiavalcons156ejl8lgmfq8ju55mde966ngge844t3w03dp5u
  index_offset: "415253"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "447689"
  tombstoned: false
- address: celestiavalcons14fk7wjrtu8k2t2hzj2vq0dpl20vc9huk6mm3dg
  index_offset: "658"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "256"
  tombstoned: false
- address: celestiavalcons14va3f2wxc3dx9tkzru8cmentunzjdrvxqjljmc
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "10"
  start_height: "0"
  tombstoned: false
- address: celestiavalcons14hsr3k8k0cugwyxqra3lmft5xtes9cyfqxe309
  index_offset: "672785"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "8"
  start_height: "96778"
  tombstoned: false
- address: celestiavalcons14u2haajyq4wfs3leplufdj26sjr8fmpc9494se
  index_offset: "288920"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "0"
  start_height: "652189"
  tombstoned: false
- address: celestiavalcons1kquzrtxupf8f7dhugfdc23yh7fg3zmm2mhwanq
  index_offset: "722850"
  jailed_until: "1970-01-01T00:00:00Z"
  missed_blocks_counter: "2"
  start_height: "0"
  tombstoned: false
pagination:
  next_key: FLUsMN7FOuMHSZIGc+8P9ekNHq/9
  total: "0"
```
