### ISSUE TITLE
Bug in tx_indexer config

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#3732]
## Context

I was trying to figure the steps we should provide DevOps on how to disable the kv indexer and enable the lightweight transaction indexer.

## Problem

On celestia-app v1.12.0, config.toml looks like this

```toml
[tx_index]

# What indexer to use for transactions
#
# The application will set which txs to index. In some cases a node operator will be able
# to decide which txs to index based on configuration set in the application.
#
# Options:
#   1) "null"
#   2) "kv" (default) - the simplest possible indexer, backed by key-value storage (defaults to levelDB; see DBBackend).
# 		- When "kv" is chosen "tx.height" and "tx.hash" will always be indexed.
#   3) "psql" - the indexer services backed by PostgreSQL.
# When "kv" or "psql" is chosen "tx.height" and "tx.hash" will always be indexed.
indexer = "null"
```

On celestia-app v1.13.0, config.toml looks like this:

```toml
# What indexer to use for transactions
#
# The application will set which txs to index. In some cases a node operator will be able
# to decide which txs to index based on configuration set in the application.
#
# Options:
#   1) "kv"
#   2) "kv" (default) - the simplest possible indexer, backed by key-value storage (defaults to levelDB; see DBBackend).
# 		- When "kv" is chosen "tx.height" and "tx.hash" will always be indexed.
#   3) "psql" - the indexer services backed by PostgreSQL.
# When "kv" or "psql" is chosen "tx.height" and "tx.hash" will always be indexed.
indexer = "kv"
```

## Acceptance Criteria

1. Fix the config so that there aren't two "kv" options. I think the first option should be "null".
2. [Tangent] Provide steps to DevOps on how to enable the lightweight tx indexer
