### ISSUE TITLE
Reconcile governance params on Arabica, Mocha, Mainnet Beta

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#4196]
## Context

@cmwaters noticed that the governance parameters for the slashing module on Mocha differ from Mainnet Beta. Same with the community tax.

## Proposal

1. Query all the governance params on Arabica, Mocha, Mainnet Beta. It would be really nice if someone built a reusable dashboard with all the parameters for all the networks. See the [specs](https://celestiaorg.github.io/celestia-app/parameters_v3.html) for a list of parameters. Most (if not all) can be queried using GRPC endpoints. You can get GRPC endpoints for each network from the [docs](https://docs.celestia.org/how-to-guides/mainnet#community-grpc-endpoints).
2. Analyze the inconsistencies. Some inconsistencies are desirable, for example the voting period on Arabica and Mocha is one day and the voting period on Mainnet Beta is one week. For any remaining parameters that are inconsistent, determine which one is desirable (likely the Mainnet Beta value).
3. Submit governance proposals on the other networks so that the parameters are consistent.
4. Get the governance proposals passed.

**Comment by 0xSY3** [comment]
Hi @rootulp ,
I'd like to work on this issue, reconciling governance parameters across Arabica, Mocha, and Mainnet Beta. I'll query parameters via gRPC and create a dashboard for comparison.

Any preferences for the dashboard's format or tooling?

**Comment by 0xSY3** [comment]
Hi @rootulp 

Thanks for the assignment!! I think a separate repo for the dashboard is the way to go... something like celestiaorg/governance-dashboard would be great.
I'm planning to use Python and Streamlit for the dashboard. It's a quick way to get an interactive web app up and running for this kind of data. I can switch to Dash later if we need more complex features.

If you approve, I'll start working on it as soon as the repo is set up.

Thanks!

**Comment by 0xSY3** [comment]
Hi @rootulp ,
I've completed the governance parameter dashboard! Here's what I've built:

1. Implemented parameter monitoring across networks:
- Direct gRPC queries for current parameter values 
- Shows mainnet-beta, mocha, and arabica parameters
- Parameter change detection with SQLite storage
- Network health status monitoring

2. Found inconsistencies between networks:
- Slashing module: Different SignedBlocksWindow values
- Community tax rates vary between networks

3. Tech Implementation:
- Built with Streamlit + Python for rapid development
- SQLite for parameter history tracking
- gRPC for direct network communication
- Automated 5-min refresh cycles

Live: [https://celestia-governance-dashboard.replit.app/]

would you like me to prepare governance proposals for reconciling the slashing module and community tax parameters with mainnet values??

Repo:https://github.com/0xSY3/Celestia-Governance-Dashboard/tree/main

**Comment by rootulp** [comment]
This is extremely helpful, thanks @0xSY3 ! 

![Image](https://github.com/user-attachments/assets/1e3f5d5c-c9f5-492b-b755-a9879b13130a)

Looks like most of the parameter discrepancies are on Mocha. My suggestion is to mirror Mainnet Beta. So on Mocha we should update these parameters:

- distribution.community_tax: 0.02
- slashing.min_signed_per_window: 0.750000000000000000
- slashing.signed_blocks_window: 10000
- slashing.slash_fraction_double_sign: 0.020000000000000000
- slashing.slash_fraction_downtime: 0.000000000000000000

Also we should update Arabica:
- slashing.signed_blocks_window: 10000

**Comment by rootulp** [comment]
Do you want to submit governance proposals on Arabica and Mocha to do that? You can reference [this gist](https://gist.github.com/rootulp/fcf5160a6506dc23a228a90d68e356bd) and [this issue](https://github.com/celestiaorg/celestia-app/issues/4060) to change a governance param.

**Comment by rootulp** [comment]
Celenium built a page for this: https://celenium.io/constants

## Arabica
- Update slashing.signed_blocks_window to 10000

## Mocha

- Update distribution.community_tax to .02
- Update gov.max_deposit_period to 7 days
- Update gov.min_deposit to 10,000 TIA
- Update slashing.min_signed_per_window to 75%
- Update slashing.signed_blocks_window to 10000
- Update slashing.slash_fraction_double_sign to 2% 
- Update slashing.slash_fraction_downtime to 0%

Note: we don't need to update the evidence parameters because they will be set via the v6 upgrade handler.

**Comment by rootulp** [comment]
# Arabica

## Before

```
celestia@validator-1:~$ celestia-appd query slashing params
params:
  downtime_jail_duration: 1m0s
  min_signed_per_window: "0.750000000000000000"
  signed_blocks_window: "5000"
  slash_fraction_double_sign: "0.020000000000000000"
  slash_fraction_downtime: "0.000000000000000000"
```

## Proposal

```json
{
  "messages": [
    {
      "@type": "/cosmos.slashing.v1beta1.MsgUpdateParams",
      "authority": "celestia10d07y265gmmuvt4z0w9aw880jnsr700jtgz4v7",
      "params": {
        "signed_blocks_window": "10000",
        "min_signed_per_window": "0.750000000000000000",
        "downtime_jail_duration": "60s",
        "slash_fraction_double_sign": "0.020000000000000000",
        "slash_fraction_downtime": "0.000000000000000000"
      }
    }
  ],
  "metadata": "",
  "deposit": "10000000000utia",
  "title": "Update Slashing Signed Blocks Window to 10000",
  "summary": "Update Slashing Signed Blocks Window to 10000",
  "expedited": false
}
```

Tx on Arabica: 9128B412B2ADAFAA54186AA3F36EC93F5FDC3FAABA6FFD991C975CA88A3B9DBE which is gov proposal 5

## Voting

Voted yes from all validators

```
celestia@validator-1:~$ celestia-appd query gov tally 5
tally:
  abstain_count: "0"
  no_count: "0"
  no_with_veto_count: "0"
  yes_count: "400000910000100"
```

**Comment by rootulp** [comment]
# Mocha

## Before

```
celestia@validator-1:~$ celestia-appd query gov params
params:
  burn_vote_veto: true
  expedited_min_deposit:
  - amount: "50000000000"
    denom: utia
  expedited_threshold: "0.667000000000000000"
  expedited_voting_period: 24h0m0s
  max_deposit_period: 48h0m0s
  min_deposit:
  - amount: "1000000000"
    denom: utia
  min_deposit_ratio: "0.010000000000000000"
  min_initial_deposit_ratio: "0.000000000000000000"
  proposal_cancel_ratio: "0.500000000000000000"
  quorum: "0.334000000000000000"
  threshold: "0.500000000000000000"
  veto_threshold: "0.334000000000000000"
  voting_period: 24h0m0s
celestia@validator-1:~$ celestia-appd query distribution params
params:
  base_proposer_reward: "0.000000000000000000"
  bonus_proposer_reward: "0.000000000000000000"
  community_tax: "0.200000000000000000"
  withdraw_addr_enabled: true
celestia@validator-1:~$ celestia-appd query slashing params
params:
  downtime_jail_duration: 1m0s
  min_signed_per_window: "0.050000000000000000"
  signed_blocks_window: "15000"
  slash_fraction_double_sign: "0.050000000000000000"
  slash_fraction_downtime: "0.010000000000000000"
```

## Proposal

```json
{
  "messages": [
    {
      "@type": "/cosmos.distribution.v1beta1.MsgUpdateParams",
      "authority": "celestia10d07y265gmmuvt4z0w9aw880jnsr700jtgz4v7",
      "params": {
        "community_tax": "0.020000000000000000",
        "base_proposer_reward": "0.000000000000000000",
        "bonus_proposer_reward": "0.000000000000000000",
        "withdraw_addr_enabled": true
      }
    },
    {
      "@type": "/cosmos.gov.v1.MsgUpdateParams",
      "authority": "celestia10d07y265gmmuvt4z0w9aw880jnsr700jtgz4v7",
      "params": {
        "min_deposit": [
          {
            "denom": "utia",
            "amount": "10000000000"
          }
        ],
        "max_deposit_period": "604800s",
        "voting_period": "86400s",
        "quorum": "0.334000000000000000",
        "threshold": "0.500000000000000000",
        "veto_threshold": "0.334000000000000000",
        "min_initial_deposit_ratio": "0.000000000000000000",
        "proposal_cancel_ratio": "0.500000000000000000",
        "proposal_cancel_dest": "",
        "expedited_voting_period": "86400s",
        "expedited_threshold": "0.667000000000000000",
        "expedited_min_deposit": [
          {
            "denom": "utia",
            "amount": "50000000000"
          }
        ],
        "burn_proposal_deposit_prevote": false,
        "burn_vote_quorum": false,
        "burn_vote_veto": true,
        "min_deposit_ratio": "0.010000000000000000"
      }
    },
    {
      "@type": "/cosmos.slashing.v1beta1.MsgUpdateParams",
      "authority": "celestia10d07y265gmmuvt4z0w9aw880jnsr700jtgz4v7",
      "params": {
        "signed_blocks_window": "10000",
        "min_signed_per_window": "0.750000000000000000",
        "downtime_jail_duration": "60s",
        "slash_fraction_double_sign": "0.020000000000000000",
        "slash_fraction_downtime": "0.000000000000000000"
      }
    }
  ],
  "metadata": "https://github.com/celestiaorg/celestia-app/issues/4196",
  "deposit": "10000000000utia",
  "title": "Update Mocha parameters to match Mainnet",
  "summary": "Update Mocha parameters to match Mainnet",
  "expedited": false
}
```

## Links
- [Gov proposal tx](https://www.mintscan.io/celestia-testnet/tx/C8D3E6E9569D87A7FF02949D1013053D893D04179F82B5FA16F9C11192F12B9F?height=7986545)
- [Gov proposal 11](https://www.mintscan.io/celestia-testnet/proposals/11)

## Voting

1. Voted yes from validator
2. On Discord, I asked Mocha validators to vote (see [message](https://discord.com/channels/638338779505229824/920642717057421393/1415397623598153922)).

**Comment by rootulp** [comment]
This issue is blocked until the Arabica and Mocha governance proposals pass. Then I need to verify the params match what is expected.

**Comment by rootulp** [comment]
Celenium says the Arabica proposal passed: https://arabica.celenium.io/proposal/5?tab=validators_votes. Confirmed the Arabica params were updated:

```
celestia@validator-1:/root$ celestia-appd query slashing params
params:
  downtime_jail_duration: 1m0s
  min_signed_per_window: "0.750000000000000000"
  signed_blocks_window: "10000"
  slash_fraction_double_sign: "0.020000000000000000"
  slash_fraction_downtime: "0.000000000000000000"
```
Mintscan says the Mocha proposal failed: https://www.mintscan.io/celestia-testnet/proposals/11 and it looks like the params weren't updated. Investigating...

The proposal failed for this reason:

```
  failed_reason: expedited voting period 24h0m0s must be strictly less that the regular
    voting period 24h0m0s
```

so two options:
Option A. Modify that check in the Cosmos SDK to enable both the voting period and expedited voting period to match. This seems preferable considering they're both 24 hours on Arabica. 
Option B. Re-submit the governance proposal with a slightly lower expedited voting period. This isn't as ideal because then the params don't match between Arabica, Mocha, and Mainnet.
