### ISSUE TITLE
Increase default `recv_rate` and `send_rate`

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#4213]
## Context

https://github.com/celestiaorg/celestia-app/blob/2e16394ecc8b06439585edb8dc16e7ff5b63f008/Makefile#L337-L348 modified the send and receive rates in config file

## Problem

The defaults for those fields are still low.

## Proposal

1. Increase the defaults so that the `configure-v3` command isn't necessary if someone downloads a new binary and generates a new config.
2. Look at the ttl-num-blocks field and see if that default also needs to be bumped

**Comment by rootulp** [comment]
On the latest v3.x binary, a freshly generated config:

```toml
# Rate at which packets can be sent, in bytes/second
send_rate = 5120000

# Rate at which packets can be received, in bytes/second
recv_rate = 5120000

# Note, if ttl-duration is also defined, a transaction will be removed if it
# has existed in the mempool at least ttl-num-blocks number of blocks or if
# it's insertion time into the mempool is beyond ttl-duration.
ttl-num-blocks = 12
```

And after running the configure-v3 command, they look like this:

```toml
# Rate at which packets can be sent, in bytes/second
send_rate = 10485760  

# Rate at which packets can be received, in bytes/second
recv_rate = 10485760  

# ttl-num-blocks, if non-zero, defines the maximum number of blocks a transaction
# can exist for in the mempool.
#
# Note, if ttl-duration is also defined, a transaction will be removed if it
# has existed in the mempool at least ttl-num-blocks number of blocks or if
# it's insertion time into the mempool is beyond ttl-duration.
ttl-num-blocks = 12
```

so the TTL num blocks default does not need to be modified. But the send and recv rates do.
