### ISSUE TITLE
Enable E2E tests to run from forks

### ISSUE THREAD

**Issue by chatton** [celestiaorg/celestia-app#4395]
### Overview  
Currently, e2e tests that utilize knuu, also utilize repository secrets (KUBECONFIG), this means that PRs from forks are not able to access the cluster.

###  Suggested Solution  
1. Create a separate workflow that deploys a small cluster (kind/minikube etc) and runs the E2E tests using that KUBECONFIG, rather than the private cluster.

Create a new workflow that only runs on forks

```yaml
name: E2E Fork

on:
  pull_request:

jobs:
  e2e-fork:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.fork == true
    ...
```
