### ISSUE TITLE
/bin/celestia-appd: cannot execute binary file: Exec format error on arm64

### ISSUE THREAD

**Issue by arcenik** [celestiaorg/celestia-app#4855]
### Summary of Bug

The celestia-appd binary in the arm64 Docker image is a amd64 binary and not arm64.

ghcr.io/celestiaorg/celestia-app:v4.0.1-mocha@sha256:a31ef1f64224975d86dfe8caa31693d5f535d94a3c42ff769850d87db8778622

I ran a few command the confirm it with the result below.

```text
+ bash --version
GNU bash, version 5.2.21(1)-release (aarch64-alpine-linux-musl)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
+ celestia-appd --version
/bin/bash: line 1: /bin/celestia-appd: cannot execute binary file: Exec format error
+ od -x -N20 /bin/bash
0000000 457f 464c 0102 0001 0000 0000 0000 0000
0000020 0003 00b7
0000024
+ od -x -N20 /bin/celestia-appd
0000000 457f 464c 0102 0001 0000 0000 0000 0000
0000020 0002 003e
0000024
```

So /bin/bash architecture is 0x00b7 (Arm 64) and /bin/celestia-appd architecture is 0x003e (Amd 64)

https://en.wikipedia.org/wiki/Executable_and_Linkable_Format

### Version

v4.0.1-mocha

### Steps to Reproduce

Here is the container definition for kubernetes pod

```yaml
        - name: validate
          image: ghcr.io/celestiaorg/celestia-app:v4.0.1-mocha@sha256:a31ef1f64224975d86dfe8caa31693d5f535d94a3c42ff769850d87db8778622
          command:
            - '/bin/bash'
            - '-cx'
            - 'bash --version; celestia-appd --version; od -x -N20 /bin/bash; od -x -N20 /bin/celestia-appd'
```
