### ISSUE TITLE
config/consensus: define default parameters

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-app#589]
Introduction ✌🏻
---
Here is the current params we have for consensus part 
```toml
# How long we wait for a proposal block before prevoting nil
timeout_propose = "3s"
# How much timeout_propose increases with each round
timeout_propose_delta = "500ms"
# How long we wait after receiving +2/3 prevotes for “anything” (ie. not a single block or nil)
timeout_prevote = "1s"
# How much the timeout_prevote increases with each round
timeout_prevote_delta = "500ms"
# How long we wait after receiving +2/3 precommits for “anything” (ie. not a single block or nil)
timeout_precommit = "1s"
# How much the timeout_precommit increases with each round
timeout_precommit_delta = "500ms"
# How long we wait after committing a block, before starting on the new
# height (this gives us a chance to receive some more precommits, even
# though we already have +2/3).
timeout_commit = "25s"

# How many blocks to look back to check existence of the node's consensus votes before joining consensus
# When non-zero, the node will panic upon restart
# if the same consensus key was used to sign {double_sign_check_height} last blocks.
# So, validators should stop the state machine, wait for some blocks, and then restart the state machine to avoid panic.
double_sign_check_height = 0

# Make progress as soon as we have all the precommits (as if TimeoutCommit = 0)
skip_timeout_commit = false

# EmptyBlocks mode and possible interval between empty blocks
create_empty_blocks = true
create_empty_blocks_interval = "0s"

# Reactor sleep duration parameters
peer_gossip_sleep_duration = "100ms"
peer_query_maj23_sleep_duration = "2s"
```

New Definition 📜 
---
We have only changed `timeout_commit` from 6 to 25 seconds. This is making other params a little bit off the charts. 
If we try to do the same as tendermint that we will have smt like this: 
```toml
timeout_propose = "15s"                           #before was 3s
timeout_propose_delta = "2500ms"                  #before was 500ms
timeout_prevote = "5s"                            #before was 1s
timeout_prevote_delta = "2500ms"                  #before was 500ms
timeout_precommit = "5s"                          #before was 1s
timeout_precommit_delta = "2500ms"                #before was 500ms
timeout_commit = "30s"                            #before was 6s and 25s
```

Notes 📝 
---
Ref: #585
